@gateway = http://localhost:8080
@token = {{login.response.body.accessToken}}

### Register
POST {{gateway}}/api/auth/register
Content-Type: application/json

{
  "email": "demo@n11.local",
  "password": "demopass123",
  "fullName": "Demo Kullanıcı"
}

### Login
# @name login
POST {{gateway}}/api/auth/login
Content-Type: application/json

{
  "email": "demo@n11.local",
  "password": "demopass123"
}

### Me
GET {{gateway}}/api/users/me
Authorization: Bearer {{token}}
