package com.n11.product.recommendation;

import com.n11.product.api.dto.ProductSummaryDto;

/**
 * One row of the recommendation strip — the product card payload plus an
 * optional one-sentence Turkish "neden ilgini çekebilir" line generated by
 * the LLM.  {@code reason} may be null when Groq is disabled or fell back.
 */
public record RecommendedItemDto(ProductSummaryDto product, String reason) {}
